version: 2
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/jacobarthurs/pgplan/cmd.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"